version: '3'
services:
  resume:
    container_name: Resume
    build: "./"
    volumes:
      - "./app/publicFiles:/app/publicFiles"
    ports:
      - "81:80"
    restart: always
    environment:
     VIRTUAL_HOST: alexboyle.net,*.alexboyle.net
networks:
  default:
    external:
      name: nginx-proxy
